site:
  name: The Gr8 Escape
  site: 'https://gr8.smartintegrate.co.za'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: ''

metadata:
  title:
    default: The Gr8 Escape
    template: '%s — The Gr8 Escape'
  description: "South Africa's highest rated Escape Room. Immersive puzzle adventures in Fourways, Johannesburg."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: The Gr8 Escape
    images:
      - url: '~/assets/images/default.png'
        width: 512
        height: 512
    type: website

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'dark'
